using System.Text.Json;

namespace KClip.Api.Services;

public record SongInfo(string Id, string Title, string Artist);

/// <summary>
/// Server-side puzzle resolution. Loads a precomputed schedule from
/// puzzle-schedule.json (generated by scripts/generate-puzzle-schedule.mjs)
/// so we don't need to replicate the JS sort/PRNG logic in C#.
/// </summary>
public static class PuzzleService
{
    private static readonly TimeSpan AestOffset = TimeSpan.FromHours(10);

    /// <summary>Epoch for day numbering: 2026-03-22 AEST (stored as 2026-03-21 UTC midnight).</summary>
    private static readonly DateTimeOffset Epoch = new(2026, 3, 21, 0, 0, 0, TimeSpan.Zero);

    /// <summary>Precomputed schedule: index = day number, value = song for that day.</summary>
    private static readonly SongInfo[] Schedule;

    /// <summary>Fast lookup: songId → SongInfo.</summary>
    public static IReadOnlyDictionary<string, SongInfo> SongLookup { get; }

    static PuzzleService()
    {
        var json = File.ReadAllText(
            Path.Combine(AppContext.BaseDirectory, "Data", "puzzle-schedule.json"));

        var entries = JsonSerializer.Deserialize<ScheduleEntry[]>(json, JsonOpts)
            ?? throw new InvalidOperationException("Failed to deserialize puzzle-schedule.json");

        Schedule = entries.Select(e => new SongInfo(e.SongId, e.Title, e.Artist)).ToArray();

        // Build lookup from all unique songs in the schedule
        SongLookup = Schedule
            .DistinctBy(s => s.Id)
            .ToDictionary(s => s.Id);
    }

    /// <summary>Get the day number for a given date string (YYYY-MM-DD). Day 1 = 2026-03-22.</summary>
    public static int GetDayNumber(string dateStr)
    {
        var date = DateTimeOffset.Parse(dateStr + "T00:00:00Z");
        return (int)(date - Epoch).TotalDays;
    }

    /// <summary>Get today's date string in AEST.</summary>
    public static string GetTodayAest()
    {
        var now = DateTimeOffset.UtcNow.ToOffset(AestOffset);
        return now.ToString("yyyy-MM-dd");
    }

    /// <summary>Resolve the puzzle for a given date. Returns the correct song.</summary>
    public static SongInfo GetPuzzleSong(string dateStr)
    {
        int dayNumber = GetDayNumber(dateStr);
        int count = Schedule.Length;
        int idx = ((dayNumber % count) + count) % count;
        return Schedule[idx];
    }

    /// <summary>Evaluate a guess against the puzzle answer.</summary>
    public static string EvaluateGuess(string songId, SongInfo answer)
    {
        if (songId == answer.Id)
            return "correct";

        if (SongLookup.TryGetValue(songId, out var guessed) &&
            string.Equals(guessed.Artist, answer.Artist, StringComparison.OrdinalIgnoreCase))
            return "partial";

        return "incorrect";
    }

    // ── Deserialization ──────────────────────────────────────────────

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private sealed class ScheduleEntry
    {
        public string SongId { get; set; } = "";
        public string Title { get; set; } = "";
        public string Artist { get; set; } = "";
    }
}
